# Generated by Django 3.1.5 on 2021-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
