# Generated by Django 3.1.5 on 2021-01-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_reservations', '0003_auto_20210129_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
